/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewData.java
 *
 * Created on Nov 18, 2013, 9:36:45 AM
 */
package sportsday;

/**
 *
 * @author Administrator
 */
import java.io.*;
import javax.swing.*;
import java.awt.*;
import java.awt.*;
import java.util.*;
import java.applet.*;
import java.awt.print.*;
import javax.swing.event.*;
import java.io.*;
import javax.imageio.*;
import java.awt.event.*;
import javax.swing.*;
import java.sql.*;


public class NewData extends javax.swing.JFrame {

    /** Creates new form NewData */
    DataInputStream db;
    String list[],table[];
    int marks[][];
    String[] school,school1,school2,school3;
    //String[] school1={"BHULI","CMRI","CTPS","FRI","MAITHON","MUGMA","SIJUA","SINDRI"},school2={"BHULI","CMRI","CTPS","FRI","MAITHON","MUGMA","SIJUA","SINDRI"},school3={"BHULI","CMRI","CTPS","FRI","MAITHON","MUGMA","SIJUA","SINDRI"};
    String clas,dataname,conn;
    Connection con;
    Statement st;
    
    public NewData() {
        clas="sun.jdbc.odbc.JdbcOdbcDriver";
        dataname="sports.mdb";
        conn="jdbc:odbc:Driver={Microsoft Access Driver (*.mdb)};DBQ="+dataname.trim();
        
        try{
            Class.forName(clas);
            con=DriverManager.getConnection(conn);
            st=con.createStatement();
        }   
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        

        initiatelist();
        
        initComponents();
        
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        
    }
    void initiatelist(){
        try{
            db=new DataInputStream(new FileInputStream("Schools.txt"));
            int l=Integer.parseInt(db.readLine());
            school=new String[l];
            
            for(int i=0;i<l;i++){
                school[i]=db.readLine().trim();
            }
            school1=school;
            school2=school;
            school3=school;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        try{
            db=new DataInputStream(new FileInputStream("Events.txt"));
            int l=Integer.parseInt(db.readLine());
            list=new String[l];
            table=new String[l];
            marks=new int[l][3];
            
            for(int i=0;i<l;i++){
                String str=db.readLine();
                
                int c=0;
                String s="",s2="";
                for(int j=0;j<str.length();j++)
                {
                    char ch=str.charAt(j);
                    
                    if(ch==','){
                        c++;
                        if(c==1){
                            list[i]=s;
                            table[i]=s2;
                        }
                        else if(c==2)
                            marks[i][0]=Integer.parseInt(s);
                        else if(c==3)
                            marks[i][1]=Integer.parseInt(s);
                        else if(c==4)
                            marks[i][2]=Integer.parseInt(s);
                        s="";
                        continue;
                    }
                    s=s+ch;
                    
                    //*****(ch!=' '&& ch!='-'&& ch!='/'&&ch!='.'&&ch!='('&&ch!=')')***//
                    
                    if((ch>='a'&&ch<='z')||(ch>='A'&&ch<='Z')||(ch>='0'&&ch<='9'))
                    s2=s2+ch;
                }
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }

        
    }
    void set123()
    {
        jScrollPane2.setVisible(true);
        jScrollPane3.setVisible(true);
        jScrollPane4.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new JList(list);
        jLabel4 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        first = new JList(school1);
        jScrollPane3 = new javax.swing.JScrollPane();
        second = new JList(school2);
        jScrollPane4 = new javax.swing.JScrollPane();
        third = new JList(school3);
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Data");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("De Nobili School, CMRI");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sports' Day Event");

        javax.swing.GroupLayout HeadingLayout = new javax.swing.GroupLayout(Heading);
        Heading.setLayout(HeadingLayout);
        HeadingLayout.setHorizontalGroup(
            HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );
        HeadingLayout.setVerticalGroup(
            HeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("List of Events:");

        jLabel6.setText("1st");

        jLabel7.setText("2nd");

        jLabel8.setText("3rd");

        first.setBackground(new java.awt.Color(255, 255, 153));
        jScrollPane2.setViewportView(first);

        second.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(second);

        third.setBackground(new java.awt.Color(140, 102, 80));
        jScrollPane4.setViewportView(third);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jButton1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTxt)
                            .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel7)
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel6)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ListClicked(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListClicked
    set123();
    int n=jList1.getSelectedIndex();
    String f="",s="",t="";
    try{
    ResultSet r=st.executeQuery("SELECT * FROM DATA WHERE EVENTS='"+table[n]+"'");
    while(r.next()){
        f=r.getString("FIRST");
        s=r.getString("SECOND");
        t=r.getString("THIRD");
    }
    first.setListData(school1);
    second.setListData(school2);
    third.setListData(school3);
    
    first.setSelectedValue(f, true);
    second.setSelectedValue(s, true);
    third.setSelectedValue(t, true);
    }catch(Exception ex){JOptionPane.showMessageDialog(this, ex);}
}//GEN-LAST:event_ListClicked

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String tb,f,s,t;
    tb=table[jList1.getSelectedIndex()];
    f=school1[first.getSelectedIndex()];
    s=school2[second.getSelectedIndex()];
    t=school3[third.getSelectedIndex()];
    
    try{
        st.execute("UPDATE DATA SET FIRST='"+f+"' , SECOND='"+s+"',THIRD='"+t+"' WHERE EVENTS='"+tb+"'");
        JOptionPane.showMessageDialog(this, "Database Updated");
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex);
    }
    
    
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewData().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Heading;
    private javax.swing.JList first;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JList second;
    private javax.swing.JList third;
    // End of variables declaration//GEN-END:variables
}
